Add nohoist to root package.json
Now when running yarn dev in app1 we get the following error:

```
error - ./app/core/components/LabeledTextField.tsx
Module not found: Can't resolve 'styled-jsx/style' in '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/app/core/components'
Error: Cannot find module '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/.next/server/pages-manifest.json'
Require stack:
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/require.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/load-components.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/api-utils.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/next-server.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/server/next.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/server/lib/start-server.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/cli/next-dev.js
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/bin/next
- /home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/@blitzjs/server/bin/next-patched
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._resolveFilename (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/module-alias/index.js:49:29)
    at Function.mod._resolveFilename (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/build/webpack/require-hook.js:4:1715)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getPagePath (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at DevServer.findPageComponents (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/next-server.js:74:296)
    at DevServer.renderErrorToHTML (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/next-server.js:134:120)
    at DevServer.renderErrorToHTML (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/server/next-dev-server.js:34:974)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.render (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/next-server.js:72:236)
    at async Object.fn (/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/next-server.js:56:580) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/require.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/load-components.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/api-utils.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/next-server/server/next-server.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/server/next.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/server/lib/start-server.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/cli/next-dev.js',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/next/dist/bin/next',
    '/home/ubuntu/projects/blitz-monorepo-example/packages/app1/node_modules/@blitzjs/server/bin/next-patched'
  ]
}
```